### ISSUE TITLE
Websocket connection gets lost after some time

### ISSUE THREAD

**Issue by fdietze** [woost/wust2#17]

**Comment by cornerman** [comment]
With nginx, we have the [proxy_read_timeout](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout) that closes the connection to the proxied server after 60s without a response from the server.

The same happens in development without nginx, is this a akka-http timeout configuration then?

**Comment by cornerman** [comment]
We could send Ping/Pong messages in our protocol and extend the timeout. Other ideas?

**Comment by cornerman** [comment]
We now have ping/pong and a reconnecting websocket in place.

How should we set the ping interval and the nginx timeout?
