### ISSUE TITLE
asset checksumming

### ISSUE THREAD

**Issue by fdietze** [woost/wust2#24]
https://github.com/sbt/sbt-digest#sbt-digest

- play templates to generate index.html?

**Comment by cornerman** [comment]
we already have e-tags and nginx sends 304 not modified if the cached version can be used. Still needed?

**Comment by cornerman** [comment]
The 304 only applies for the index.html, still all included js files are cached. But if we create an index.html sourcing js files with a fingerprint in their filename, we get proper browser cache invalidation.
