### ISSUE TITLE
Delete post strategy

### ISSUE THREAD

**Issue by GRBurst** [woost/wust2#47]
What happens if a post is deleted? Currently it is gone in a sense that you can not see it anymore.
I suggest to display them as read-only with an `deleted` tag. If a post is deleted due to a merge with another post, a link to the merged post should be presented or the user should get redirected to that post

**Comment by cornerman** [comment]
Agree, we should probably also add a deleteposts view in postgres, similar like the post view (filtering on rawpost).

**Comment by fdietze** [comment]
I think deleted posts should be hidden by default. One can activate a UI option to see the history. Ideally the history also includes a post edit-history.
